work day part:
    cargo watch -c -C {{day}} -x "check -p {{day}}" -s "just test {{part}} -p {{day}}" -s "just lint {{day}}" -s "just bench {{day}} {{part}}" -s "cargo run -p {{day}} --bin {{part}}" 
lint day:
    # clippy-tracing --action check --exclude target --exclude benches
    cargo clippy -p {{day}}
test part +FLAGS='-p day-01':
    cargo nextest run {{FLAGS}} {{part}}
bench-all:
    cargo bench -q > benchmarks/all.txt
bench day part:
    cargo bench --bench {{day}} {{part}} >> benchmarks/{{day}}.txt
flamegraph day part:
    cargo flamegraph --profile flamegraph --root --package {{day}} --bin {{part}} -o flamegraphs/{{day}}-{{part}}.svg
create day:
    cargo generate --path ./daily-template --name {{day}}